version: "3"
services:
    postgres:
        image: postgres:latest
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=carbon_dev
        volumes:
            - ~/data:/var/lib/postgresql/data
    go:
        build: .
        depends_on:
            - "postgres"
        command: go run app.go
        volumes:
            - ../..:/goworkspace/src/github.com
        links:
            - postgres
        ports:
            - "3000:3000"
        restart: on-failure

